openapi: 3.0.1
info:
  title: Gemini
  description: ''
  version: 1.0.0
tags: []
paths:
  /models/gemini-2.0-flash:generateContent:
    post:
      summary: Gemini
      deprecated: false
      description: ''
      tags: []
      parameters:
        - name: key
          in: query
          description: ''
          required: false
          example: GEMINI_API_KEY
          schema:
            type: string
        - name: Content-Type
          in: header
          description: ''
          required: false
          example: application/json
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                contents:
                  type: array
                  items:
                    type: object
                    properties:
                      role:
                        type: string
                      parts:
                        type: array
                        items:
                          type: object
                          properties:
                            text:
                              type: string
                          required:
                            - text
                    required:
                      - parts
                      - role
                generationConfig:
                  type: object
                  properties:
                    response_mime_type:
                      type: string
                    response_schema:
                      type: object
                      properties:
                        type:
                          type: string
                        items:
                          type: object
                          properties:
                            type:
                              type: string
                            properties:
                              type: object
                              properties: {}
                          required:
                            - type
                            - properties
                      required:
                        - type
                        - items
                  required:
                    - response_mime_type
                    - response_schema
              required:
                - contents
            examples: {}
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  candidates:
                    type: array
                    items:
                      type: object
                      properties:
                        content:
                          type: object
                          properties:
                            parts:
                              type: array
                              items:
                                type: object
                                properties:
                                  text:
                                    type: string
                            role:
                              type: string
                          required:
                            - parts
                            - role
                required:
                  - candidates
          headers: {}
      security: []
components:
  schemas: {}
  securitySchemes: {}
servers: []
security: []
